apiVersion: apps/v1
kind: Deployment
metadata:
  name: winter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: winter-app
  template:
    metadata:
      labels:
        app: winter-app
    spec:
      containers:
      - name: winter-app
        image: winter-app:latest
        ports:
        - containerPort: 80
