apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: winter-ingress
spec:
  rules:
  - host: newton.frii.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: winter-app-service
            port:
              number: 80
